// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CheckIPv6Connectivity():Promise<main.IPv6Status>;

export function CheckSTUN():Promise<main.STUNResult>;

export function FetchAddressList(arg1:string):Promise<string>;

export function GetFiles():Promise<Array<main.FileItem>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetUpdateURL():Promise<string>;

export function IsUpdateMode():Promise<boolean>;

export function LoadSettings():Promise<config.Settings>;

export function PerformUpdate():Promise<void>;

export function ResetSettings():Promise<config.Settings>;

export function RestartApp():Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function TestTCPLatency(arg1:string,arg2:number,arg3:number):Promise<number>;

export function ToggleFile(arg1:string,arg2:boolean):Promise<void>;
