// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIPv6Connectivity() {
  return window['go']['main']['App']['CheckIPv6Connectivity']();
}

export function CheckSTUN() {
  return window['go']['main']['App']['CheckSTUN']();
}

export function FetchAddressList(arg1) {
  return window['go']['main']['App']['FetchAddressList'](arg1);
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetUpdateURL() {
  return window['go']['main']['App']['GetUpdateURL']();
}

export function IsUpdateMode() {
  return window['go']['main']['App']['IsUpdateMode']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function PerformUpdate() {
  return window['go']['main']['App']['PerformUpdate']();
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function TestTCPLatency(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestTCPLatency'](arg1, arg2, arg3);
}

export function ToggleFile(arg1, arg2) {
  return window['go']['main']['App']['ToggleFile'](arg1, arg2);
}
